package util;

public enum RequiredElementMaintenance {
	EXECUTION_DATE, STARTDATE_REQUIRED, ENDDATE_REQUIRED, TECHNICIAN_REQUIRED, REASON_REQUIRED, MAINTENANCESTATUS_REQUIRED,
	MACHINE_REQUIRED, END_DATE_BEFORE_START, START_TIME_REQUIRED, END_TIME_REQUIRED, START_DATE_REQUIRED, END_DATE_REQUIRED
}
