package util;

public enum RequiredElementMachine
{
	CODE_REQUIRED, MACHINESTATUS_REQUIRED, PRODUCTIONSTATUS_REQUIRED, LOCATION_REQUIRED, PRODUCTINFO_REQUIRED,
	SITE_REQUIRED, TECHNICIAN_REQUIRED, LAST_MAINTENANCE_REQUIRED, FUTURE_MAINTENANCE_REQUIRED
}
