package util;

public enum RequiredElementMachine {
    CODE_REQUIRED,
    STATUS_REQUIRED,
    PRODUCTIE_STATUS_REQUIRED,
    LOCATION_REQUIRED,
    PRODUCT_INFO_REQUIRED,
    SITE_REQUIRED,
    TECHNICIAN_REQUIRED,
    LAST_MAINTENANCE_REQUIRED,
    FUTURE_MAINTENANCE_REQUIRED
}
