package util;

public enum RequiredElementMaintenance {
	EXECUTION_DATE_REQUIRED, TECHNICIAN_REQUIRED, REASON_REQUIRED, MAINTENANCESTATUS_REQUIRED, END_DATE_REQUIRED,
	MACHINE_REQUIRED, END_DATE_BEFORE_START, START_DATE_REQUIRED
}
