package util;

public enum RequiredElementReport
{
	SITE_REQUIRED, MAINTENANCENUMBER_REQUIRED, MAINTENANCE_REQUIRED, TECHNICIAN_REQUIRED, STARTDATE_REQUIRED,
	STARTTIME_REQUIRED, ENDDATE_REQUIRED, ENDTIME_REQUIRED, REASON_REQUIRED, END_DATE_BEFORE_START,
	END_TIME_BEFORE_START
}
